### ISSUE TITLE
Spectural Normalization

### ISSUE THREAD

**Issue by weizequan** [Jittor/JGAN#14]
Is there any implementation of spectral normalization? Thanks!

**Comment by zhouwy19** [comment]
Hello,

Can you try to implement it accroding to [this](https://github.com/christiancosgrove/pytorch-spectral-normalization-gan/blob/master/spectral_normalization.py)? Ask me if you have any problem.

**Comment by zhouwy19** [comment]
There is an implementation. You can have a try.

https://discuss.jittor.org/t/topic/194/3
